#!/usr/bin/env python3
"""Second pass: split 'general' into many focused groups."""

import csv, collections

RECLASSIFY = {
    # ── geography ─ Greek cities/islands/regions, foreign cities, landmarks ──
    'Αγρίνιο':             'geography',
    'Αμοργός':             'geography',
    'Ανδριανούπολη':       'geography',
    'Άνω Πορόια':          'geography',
    'Αργοστόλι':           'geography',
    'Άργος':               'geography',
    'Αστεροσκοπείο':       'geography',
    'Αστυπάλαια':          'geography',
    'Άιφελ Πύργος':        'geography',
    'Βαλτική':             'geography',
    'Βαρκελώνη':           'geography',
    'Γιάννενα':            'geography',
    'Δήλος':               'geography',
    'Δράμα':               'geography',
    'Δωδεκάνησα':          'geography',
    'Έβρος':               'geography',
    'Ζάκυνθος':            'geography',
    'Ζυρίχη':              'geography',
    'Θεσσαλονίκη':         'geography',
    'Θερμαϊκός':           'geography',
    'Θιβέτ':               'geography',
    'Καλαμάτα':            'geography',
    'Καμάρα':              'geography',
    'Κηφισιά':             'geography',
    'Κομοτηνή':            'geography',
    'Κρήτη':               'geography',
    'Κυκλάδες':            'geography',
    'Λάρισα':              'geography',
    'Λάρνακα':             'geography',
    'Λευκός Πύργος':       'geography',
    'Λούβρο':              'geography',
    'Μεσόγειος':           'geography',
    'Μπαξέδες':            'geography',
    'Μύκονος':             'geography',
    'Ναύπακτος':           'geography',
    'Ντουμπάι':            'geography',
    'Ξάνθη':               'geography',
    'Πελοπόννησος':        'geography',
    'Πέραν':               'geography',
    'Πυραμίδα':            'geography',
    'Πύργος του Άιφελ':    'geography',
    'Σαμοθράκη':           'geography',
    'Σίδνεϋ':              'geography',
    'Σμύρνη':              'geography',
    'Σποράδες':            'geography',
    'Τρίπολη':             'geography',
    'Φανάρι':              'geography',
    'Χαλκιδική':           'geography',
    'Χανιά':               'geography',
    'Χίος':                'geography',

    # ── professions ─ job titles and occupational roles ───────────────────────
    'αεροσυνοδός':         'professions',
    'ανθοπώλης':           'professions',
    'αρχιτέκτονας':        'professions',
    'βιβλιοπώλης':         'professions',
    'γαλατάς':             'professions',
    'γεωπόνος':            'professions',
    'γεωργός':             'professions',
    'γραμματέας':          'professions',
    'γραφίστας':           'professions',
    'δικηγόρος':           'professions',
    'ηλεκτρολόγος':        'professions',
    'καπετάνιος':          'professions',
    'καστανάς':            'professions',
    'κηπουρός':            'professions',
    'κρεοπώλης':           'professions',
    'κρεοπωλείο':          'professions',
    'μαθηματικός':         'professions',
    'μάγειρας':            'professions',
    'μανάβης':             'professions',
    'μανάβικο':            'professions',
    'μελισσοκόμος':        'professions',
    'μηχανικός':           'professions',
    'μπακάλης':            'professions',
    'μόδιστρος':           'professions',
    'ναύτης':              'professions',
    'νομικός':             'professions',
    'πυροσβέστης':         'professions',
    'ράφτης':              'professions',
    'σαλεπτζής':           'professions',
    'σεφ':                 'professions',
    'τροχονόμος':          'professions',
    'φωτογράφος':          'professions',
    'χτίστης':             'professions',
    'ψιλικατζής':          'professions',

    # ── travel ─ tourism, trips, accommodation, transport ─────────────────────
    'αεροπλάνο':           'travel',
    'άφιξη':               'travel',
    'αναχώρηση':           'travel',
    'απογείωση':           'travel',
    'αξιοθέατο':           'travel',
    'βίλα':                'travel',
    'διαμονή':             'travel',
    'εκδρομή':             'travel',
    'θέρετρο':             'travel',
    'ημιδιατροφή':         'travel',
    'κάμπιγκ':             'travel',
    'κατασκήνωση':         'travel',
    'κατάλυμα':            'travel',
    'κράτηση':             'travel',
    'κρουαζιέρα':          'travel',
    'ξεναγός':             'travel',
    'ξενώνας':             'travel',
    'παράλια':             'travel',
    'προορισμός':          'travel',
    'προσγείωση':          'travel',
    'πτήση':               'travel',
    'ράφτιγκ':             'travel',
    'σαφάρι':              'travel',
    'τελωνείο':            'travel',
    'τουρισμός':           'travel',
    'τουρίστας':           'travel',
    'τουριστικός':         'travel',
    'ταξιδιωτικός':        'travel',

    # ── shopping ─ commerce, buying, selling ──────────────────────────────────
    'αγοραπωλησία':        'shopping',
    'αγορασμένος':         'shopping',
    'αντικαταβολή':        'shopping',
    'αποστολή':            'shopping',
    'διανομή':             'shopping',
    'έκπτωση':             'shopping',
    'εκπτώσεις':           'shopping',
    'εκπτωτικός':          'shopping',
    'εμπόρευμα':           'shopping',
    'εμπορικός':           'shopping',
    'εμπόριο':             'shopping',
    'έμπορος':             'shopping',
    'κατάλογος':           'shopping',
    'παραγγελία':          'shopping',
    'παραλαβή':            'shopping',
    'πελάτης':             'shopping',
    'περίπτερο':           'shopping',
    'πορτοφόλι':           'shopping',
    'προπώληση':           'shopping',
    'προσφορά':            'shopping',
    'πώληση':              'shopping',
    'ταμίας':              'shopping',
    'ψώνια':               'shopping',

    # ── holidays ─ celebrations, traditions, customs ──────────────────────────
    'Αληθώς Ανέστη!':      'holidays',
    'αποκριάτικος':        'holidays',
    'αρραβωνιαστικός':     'holidays',
    'βάφτιση':             'holidays',
    'γιορτή':              'holidays',
    'γιορταστικός':        'holidays',
    'δεξίωση':             'holidays',
    'έθιμο':               'holidays',
    'κάλαντα':             'holidays',
    'κουμπάρα':            'holidays',
    'μπομπονιέρα':         'holidays',
    'να ζήσετε!':          'holidays',
    'Πάσχα':               'holidays',
    'παράδοση':            'holidays',
    'ρεβεγιόν':            'holidays',
    'στολίδι':             'holidays',
    'στολισμένος':         'holidays',
    'Χριστός Ανέστη!':     'holidays',
    'Χριστούγεννα':        'holidays',
    'χρόνια πολλά!':       'holidays',

    # ── food additions ────────────────────────────────────────────────────────
    'αγκινάρα':            'food',
    'αλεύρι':              'food',
    'αλμύρα':              'food',
    'αλοιφή':              'food',
    'αμύγδαλο':            'food',
    'αμυγδαλωτός':         'food',
    'αναψυκτικό':          'food',
    'ανανάς':              'food',
    'αχλάδι':              'food',
    'αραιωμένος':          'food',
    'αρωματικός':          'food',
    'αρωματισμός':         'food',
    'βανίλια':             'food',
    'βαρέλι':              'food',
    'βασιλικός':           'food',
    'βερίκοκο':            'food',
    'βραστός':             'food',
    'γαλακτοκομικός':      'food',
    'γεμιστά':             'food',
    'γεμιστές πιπεριές':   'food',
    'γεύση':               'food',
    'γευστικός':           'food',
    'γιαούρτι':            'food',
    'γλυκό':               'food',
    'γλυκό του ταψιού':    'food',
    'γλύκα':               'food',
    'γύρος':               'food',
    'δημητριακά':          'food',
    'δυόσμος':             'food',
    'ζαμπόν':              'food',
    'ζουμερός':            'food',
    'ζυμαρικό':            'food',
    'ζύμη':                'food',
    'ζύμωμα':              'food',
    'θαλασσινά':           'food',
    'θρεπτικός':           'food',
    'καλαμαράκι':          'food',
    'καλαμπόκι':           'food',
    'κάρδαμο':             'food',
    'καρπούζι':            'food',
    'καρότο':              'food',
    'καρύδα':              'food',
    'καρύδι':              'food',
    'καρύκευμα':           'food',
    'κεφτές':              'food',
    'κολοκυθάκι':          'food',
    'κολοκύθι':            'food',
    'κολοκυθόπιτα':        'food',
    'κονιάκ':              'food',
    'κουνουπίδι':          'food',
    'κουσκούσι':           'food',
    'κουταλιά':            'food',
    'κριθάρι':             'food',
    'κροκέτα':             'food',
    'κροκάδι':             'food',
    'λαχανικά':            'food',
    'λάχανο':              'food',
    'λεμονάδα':            'food',
    'λικέρ':               'food',
    'λουκάνικο':           'food',
    'λουκουμάς':           'food',
    'μαγειρεμένος':        'food',
    'μαγειρική':           'food',
    'μαγιά':               'food',
    'μαϊντανός':           'food',
    'μακαρόνια':           'food',
    'μαστίχα':             'food',
    'μαχλέπι':             'food',
    'μείγμα':              'food',
    'μελιτζάνα':           'food',
    'μελιτζανοσαλάτα':     'food',
    'μέντα':               'food',
    'μερίδα':              'food',
    'μεζές':               'food',
    'μπαχαρικό':           'food',
    'μπέικιν πάουντερ':    'food',
    'μπέικον':             'food',
    'μπιφτέκι':            'food',
    'μπολ':                'food',
    'μπρόκολο':            'food',
    'μύδι':                'food',
    'μύδια σαγανάκι':      'food',
    'νοστιμιά':            'food',
    'ντάκος':              'food',
    'ντολμάς':             'food',
    'ντόνατ':              'food',
    'ομελέτα':             'food',
    'όσπριο':              'food',
    'ούζο':                'food',
    'παντζάρι':            'food',
    'παπάγια':             'food',
    'παξιμάδι':            'food',
    'πατατάκια':           'food',
    'πεπόνι':              'food',
    'πίκλα':               'food',
    'πικρός':              'food',
    'πίτα':                'food',
    'πίτσα':               'food',
    'πουρές':              'food',
    'ρακή':                'food',
    'ρεβίθι':              'food',
    'ριγάνη':              'food',
    'ροδάκινο':            'food',
    'ρόδι':                'food',
    'ρόκα':                'food',
    'σαλάμι':              'food',
    'σαμπάνια':            'food',
    'σαρδέλα':             'food',
    'σκόρδο':              'food',
    'σόδα':                'food',
    'σολομός':             'food',
    'σουβλάκι':            'food',
    'σπαγγέτι':            'food',
    'σπανάκι':             'food',
    'σπανακόπιτα':         'food',
    'σταφίδα':             'food',
    'σταφύλι':             'food',
    'στραγάλι':            'food',
    'τηγανητός':           'food',
    'τζατζίκι':            'food',
    'τυροσαλάτα':          'food',
    'φακή':                'food',
    'φιστίκι':             'food',
    'φλούδι':              'food',
    'φράουλα':             'food',
    'χαμομήλι':            'food',
    'χαλβάς':              'food',
    'χόρτα':               'food',
    'χορτασμένος':         'food',
    'χορταστικός':         'food',
    'χυλός':               'food',
    'ψημένος':             'food',
    'ψήσιμο':              'food',
    'ξύδι':                'food',
    'ξύσμα':               'food',

    # ── home additions ────────────────────────────────────────────────────────
    'ανακαίνιση':          'home',
    'ανακαινισμένος':      'home',
    'ασανσέρ':             'home',
    'ατμομάγειρας':        'home',
    'βεράντα':             'home',
    'θέρμανση':            'home',
    'εισόδος':             'home',
    'κάδος':               'home',
    'καλοριφέρ':           'home',
    'κλειδαριά':           'home',
    'κουζίνα ηλεκτρική':   'home',
    'κουρτίνα':            'home',
    'κρεβατοκάμαρα':       'home',
    'μίξερ':               'home',
    'μπανιέρα':            'home',
    'ντουλάπα':            'home',
    'ντουλάπι':            'home',
    'πιλοτή':              'home',
    'πλακάκι':             'home',
    'ράφι':                'home',
    'ρετιρέ':              'home',
    'σόφιτα':              'home',
    'στρώμα':              'home',
    'υπνοδωμάτιο':         'home',
    'φούρνος μικροκυμάτων': 'home',
    'χαγιάτι':             'home',
    'χολ':                 'home',
    'ψυγείο':              'home',

    # ── body additions ────────────────────────────────────────────────────────
    'αφαλός':              'body',
    'αστράγαλος':          'body',
    'βλεφαρίδα':           'body',
    'εγκέφαλος':           'body',
    'γόνατο':              'body',
    'καρπός':              'body',
    'κόκαλο':              'body',
    'κότσος':              'body',
    'κούρεμα':             'body',
    'κρανίο':              'body',
    'λαιμός':              'body',
    'μάγουλο':             'body',
    'μέση':                'body',
    'μέτωπο':              'body',
    'μουστάκι':            'body',
    'μούσι':               'body',
    'μυς':                 'body',
    'νύχι':                'body',
    'οστό':                'body',
    'πιγούνι':             'body',
    'πνεύμονας':           'body',
    'ρυτίδα':              'body',
    'σπυρί':               'body',
    'φαλάκρα':             'body',
    'χτένισμα':            'body',

    # ── clothes additions ─────────────────────────────────────────────────────
    'βερμούδα':            'clothes',
    'γιακάς':              'clothes',
    'γούνα':               'clothes',
    'γούνινος':            'clothes',
    'ζιβάγκο':             'clothes',
    'κουμπί':              'clothes',
    'μανίκι':              'clothes',
    'μαντίλι':             'clothes',
    'μπότα':               'clothes',
    'ντεκολτέ':            'clothes',
    'ντυμένος':            'clothes',
    'ντύσιμο':             'clothes',
    'πουλόβερ':            'clothes',
    'σαγιονάρα':           'clothes',
    'σακίδιο':             'clothes',
    'σανδάλι':             'clothes',
    'σαρίκι':              'clothes',
    'φέσι':                'clothes',
    'φόρμα':               'clothes',
    'φερμουάρ':            'clothes',

    # ── city / transport additions ────────────────────────────────────────────
    'κίνηση':              'city',
    'κυκλοφορία':          'city',
    'κυκλοφοριακός':       'city',
    'καύσιμο':             'city',
    'κράνος':              'city',
    'διόδια':              'city',
    'λάστιχο':             'city',
    'μέσα μεταφοράς':      'city',
    'μεταφορά':            'city',
    'μεταφορικό μέσο':     'city',
    'μεταφορικός':         'city',
    'μετακίνηση':          'city',
    'μποτιλιάρισμα':       'city',
    'όχημα':               'city',
    'σιδηροδρομικός':      'city',
    'συγκοινωνία':         'city',
    'ταχύτητα':            'city',
    'τέρμα λεωφορείου':    'city',
    'γειτονιά':            'city',
    'γειτονικός':          'city',
    'περιοχή':             'city',
    'συνοικία':            'city',
    'δήμος':               'city',
    'δημοτικός':           'city',
    'αστικός':             'city',

    # ── music / arts additions ────────────────────────────────────────────────
    'αυτοσχεδιασμός':      'music',
    'αυτοσχέδιος':         'music',
    'γλυπτική':            'music',
    'θέαμα':               'music',
    'θεατής':              'music',
    'θεατρικό έργο':       'music',
    'θεατρικός':           'music',
    'κινηματογραφικός':    'music',
    'κινούμενα σχέδια':    'music',
    'κωμωδία':             'music',
    'λογοτεχνία':          'music',
    'λογοτεχνικός':        'music',
    'μυθιστόρημα':         'music',
    'παντομίμα':           'music',
    'παράσταση':           'music',
    'πινακοθήκη':          'music',
    'ποίημα':              'music',
    'ποίηση':              'music',
    'σκηνή':               'music',
    'σκηνικό':             'music',
    'σκηνοθέτης':          'music',
    'φιλολογία':           'music',
    'χορός':               'music',

    # ── people additions ─ family members ────────────────────────────────────
    'αυτοκράτορας':        'people',
    'ανιψιά':              'people',
    'ανιψιός':             'people',
    'βασιλόπουλο':         'people',
    'γαμπρός':             'people',
    'γιαγιά':              'people',
    'γιος':                'people',
    'εγγόνι':              'people',
    'εγγονή':              'people',
    'εγγονός':             'people',
    'ήρωας':               'people',
    'θεία':                'people',
    'θείος':               'people',
    'κόρη':                'people',
    'μαμά':                'people',
    'νύφη':                'people',
    'παιδιά':              'people',
    'παππούς':             'people',
    'πεθερός':             'people',
    'ξάδερφος':            'people',

    # ── society additions ────────────────────────────────────────────────────
    'αδικία':              'society',
    'ανεργία':             'society',
    'βία':                 'society',
    'δημοκρατία':          'society',
    'δουλεία':             'society',
    'έγκλημα':             'society',
    'εκλογή':              'society',
    'ειρήνη':              'society',
    'εθελοντής':           'society',
    'εθελοντικός':         'society',
    'παράνομος':           'society',
    'πόλεμος':             'society',
    'στρατός':             'society',
    'στρατιώτης':          'society',
    'στρατιωτικός':        'society',
    'τρομοκρατία':         'society',
    'τρομοκρατημένος':     'society',

    # ── health additions ─────────────────────────────────────────────────────
    'αρρώστια':            'health',
    'εγκυμοσύνη':          'health',
    'ζάλη':                'health',
    'ζαλισμένος':          'health',
    'περαστικά!':          'health',

    # ── money additions ───────────────────────────────────────────────────────
    'αποζημίωση':          'money',
    'δάνειο':              'money',
    'δανεισμός':           'money',
    'δανειστικός':         'money',
    'επένδυση':            'money',
    'έσοδο':               'money',
    'εισόδο':              'money',
    'ευρώ':                'money',
    'κέρμα':               'money',
    'λογαριασμός':         'money',
    'μισθός':              'money',
    'νόμισμα':             'money',
    'πιστωτικός':          'money',
    'πληρωμή':             'money',
    'πλούτος':             'money',
    'πλούσιος':            'money',

    # ── school / education additions ──────────────────────────────────────────
    'εκπαίδευση':          'school',
    'εξετάσεις':           'school',
    'επαγγελματισμός':     'school',
    'σπουδές':             'school',
    'σχολικός':            'school',
    'ΑΕΙ (Ανώτατο Εκπαιδευτικό Ίδρυμα)': 'school',
    'απολυτήριο':          'school',
    'βοήθημα':             'school',
    'διάβασμα':            'school',
    'διδασκαλία':          'school',
    'δίδακτρα':            'school',
    'εξάμηνο':             'school',
    'εξεταστής':           'school',
    'επαγγελματίας':       'school',
    'πτυχίο':              'school',
    'υποτροφία':           'school',
}


def regroup(input_file, output_file):
    with open(input_file, encoding='utf-8') as f:
        rows = list(csv.reader(f))

    changed = 0
    group_counts: dict[str, int] = {}

    for i, row in enumerate(rows):
        if i == 0 or len(row) < 6:
            continue
        greek = row[1]
        if greek in RECLASSIFY:
            new_group = RECLASSIFY[greek]
            if row[5] != new_group:
                row[5] = new_group
                changed += 1
                group_counts[new_group] = group_counts.get(new_group, 0) + 1

    with open(output_file, 'w', encoding='utf-8', newline='') as f:
        csv.writer(f).writerows(rows)

    print(f'Group changes: {changed}')
    for g, c in sorted(group_counts.items()):
        print(f'  → {g}: {c} words')


if __name__ == '__main__':
    regroup('words.csv', 'words.csv')

    with open('words.csv', encoding='utf-8') as f:
        reader = csv.reader(f)
        next(reader)
        counts = collections.Counter(row[5] for row in reader if len(row) > 5)
    print('\nFinal group sizes:')
    for g, c in sorted(counts.items(), key=lambda x: -x[1]):
        flag = ' ⚠️  (<10)' if c < 10 else ''
        print(f'  {c:5d}  {g}{flag}')
